kafka:
  image:
    tag: 3.4
  listeners:
    client:
      protocol: PLAINTEXT
  controller:
    replicaCount: 3
    controllerOnly: false
    pdb:
      create: true
      maxUnavailable: 1
  broker:
    replicaCount: 0
    pdb:
      create: false
      maxUnavailable: 1
  kraft:
    enabled: true
  zookeeper:
    enabled: false
  sasl:
    enabledMechanisms: PLAIN
  provisioning:
    enabled: true
    topics:
      - name: posts
        partitions: 3
        replicationFactor: 3

consumer:
  image:
    repository: johnpaulkj/kafka-consumer
    pullPolicy: Always
    tag: "latest"

producer:
  image:
    repository: johnpaulkj/kafka-producer
    pullPolicy: Always
    tag: "latest"