apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bm-app.name" . }}-consumer
  labels:
    {{- include "bm-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "bm-app.name" . }}-consumer
    app.kubernetes.io/part-of: kafka-client
spec:
  selector:
    matchLabels:
      {{- include "bm-app.labels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "bm-app.name" . }}-consumer
      app.kubernetes.io/part-of: kafka-client
  template:
    metadata:
      labels:
        {{- include "bm-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "bm-app.name" . }}-consumer
        app.kubernetes.io/part-of: kafka-client
    spec:
      initContainers:
        - name: init-container
          image: registry.access.redhat.com/ubi8/ubi:latest
          command: ['sh', '-c', 'until getent hosts $KAFKA_BROKER_URL; do echo waiting for $KAFKA_BROKER_URL; sleep 2; done;']
          env:
            - name: KAFKA_BROKER_URL
              value: "buildingminds-kafka"
      containers:
        - name: {{ include "bm-app.name" . }}-consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER_URL
              value: "buildingminds-kafka:9092"
            - name: KAFKA_TOPIC
              value: "posts"